blogs/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',include('myapp.urls',namespace='myapp'))
]

myapp/tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)
from django.conf.urls import url

from tinymce import views

urlpatterns = [
    url(r'^spellchecker/$', views.spell_check, name='tinymce-spellcheck'),
    url(r'^flatpages_link_list/$', views.flatpages_link_list, name='tinymce-linklist'),
    url(r'^compressor/$', views.compressor, name='tinymce-compressor'),
    url(r'^filebrowser/$', views.filebrowser, name='tinymce-filebrowser'),
]

myapp/urls.py
from django.urls import path
from myapp.views import *

app_name='myapp'

urlpatterns = [
    path('first/',New_article,name='first'),
    path('category/<int:cid>',category,name='category'),
    path('acticle_page/',acticle_page,name='acticle_page'),
    path('article/',article,name='article'),
    path('reg/',reg,name='reg'),
    path('reg1/',reg1,name='reg1'),
    path('login/<aid>/',gologin,name='login'),
    path('login1/',login1,name='login1'),
    path('logout/',log_out,name='logout'),
    path('cmt1/<aid>/',cmt1,name='cmt1'),

]

myapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class Myuser(AbstractUser):
    weixin=models.CharField(max_length=10,verbose_name = '微信号')
    phone=models.CharField(max_length=10,verbose_name = '联系电话')

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = '用户'
        ordering = ['id']






class Category(models.Model):
    name = models.CharField(max_length = 10,verbose_name = '种类名字')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '种类'
        verbose_name_plural = '种类'
        ordering=['id']

class Tag(models.Model):
    name=models.CharField(max_length = 50,verbose_name ='标签名称',)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = '标签'
        verbose_name_plural = '标签'



class Article(models.Model):
    title =  models.TextField(verbose_name = '文章标题')
    desc = models.CharField(max_length=50,verbose_name = '文章简介')
    content = models.TextField(verbose_name='文章内容')
    date_publish = models.DateField(auto_now_add=True,verbose_name = '提交时间')
    click_count = models.IntegerField(verbose_name = '点击次数')

    user = models.ForeignKey(Myuser,on_delete=models.CASCADE,verbose_name = '所属用户')
    category_name = models.ForeignKey(Category,on_delete=models.CASCADE,verbose_name = '文章类型')
    tag = models.ManyToManyField(Tag,through='Article_Tag')
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = '文章'
        ordering=['-date_publish']


class Article_Tag(models.Model):
    tag=models.ForeignKey(Tag,on_delete=models.CASCADE)
    article=models.ForeignKey(Article,on_delete=models.CASCADE)


class Comment(models.Model):
    username = models.CharField(max_length=12,verbose_name='评论的用户')
    content = models.TextField(verbose_name='评论内容')
    date_publish = models.DateField(auto_now_add = True,verbose_name='评论时间')
    article_comment = models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name='评论的对象文章')
    parent_cmt = models.ForeignKey('Comment',on_delete=models.CASCADE,null=True,blank=True,verbose_name='父评论')

    def __str__(self):
        return self.username
    class Meta:
        verbose_name = '评论'
        verbose_name_plural = '评论'

myapp/tinymce/models.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

from django.db import models
from django.contrib.admin import widgets as admin_widgets
from tinymce import widgets as tinymce_widgets
try:
    from south.modelsinspector import add_introspection_rules
    add_introspection_rules([], ['^tinymce\.models\.HTMLField'])
except ImportError:
    pass


class HTMLField(models.TextField):
    """
    A large string field for HTML content. It uses the TinyMCE widget in
    forms.
    """
    def formfield(self, **kwargs):
        defaults = {'widget': tinymce_widgets.TinyMCE}
        defaults.update(kwargs)

        # As an ugly hack, we override the admin widget
        if defaults['widget'] == admin_widgets.AdminTextareaWidget:
            defaults['widget'] = tinymce_widgets.AdminTinyMCE

        return super(HTMLField, self).formfield(**defaults)

myapp/forms.py
# from django import forms
#
# class Mycomment(forms.Form):
#     name =  forms.CharField(max_length = 10,label = '名称')
#     content = forms.CharField(max_length = 100,label = '评论内容')
#     date_publish = forms.DateField(auto_now_add = True,label = '评论时间')
#     url = forms.CharField(max_length=20,label = '地址')

myapp/tinymce/views.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

import json
import logging

import django
if django.VERSION < (2,):  # pragma: no cover
    import warnings
    warnings.warn("Support for Django < 2.0 will be removed soon,"
                  "please upgrade your projects to use Django 2.0", DeprecationWarning)

from django.http import HttpResponse
from django.shortcuts import render
from django.utils.encoding import force_text
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_exempt
try:
    from django.urls import reverse
except ImportError:
    # Django < 1.10
    from django.core.urlresolvers import reverse

from tinymce.compressor import gzip_compressor

try:
    import enchant
except ImportError:
    enchant = None


@csrf_exempt
def spell_check(request):
    """
    Returns a HttpResponse that implements the TinyMCE spellchecker protocol.
    """
    try:
        if not enchant:
            raise RuntimeError("install pyenchant for spellchecker functionality")

        raw = force_text(request.body)
        input = json.loads(raw)
        id = input['id']
        method = input['method']
        params = input['params']
        lang = params[0]
        arg = params[1]

        if not enchant.dict_exists(str(lang)):
            raise RuntimeError("dictionary not found for language {!r}".format(lang))

        checker = enchant.Dict(str(lang))

        if method == 'checkWords':
            result = [word for word in arg if word and not checker.check(word)]
        elif method == 'getSuggestions':
            result = checker.suggest(arg)
        else:
            raise RuntimeError("Unknown spellcheck method: {!r}".format(method))
        output = {
            'id': id,
            'result': result,
            'error': None,
        }
    except Exception:
        logging.exception("Error running spellchecker")
        return HttpResponse(_("Error running spellchecker"))
    return HttpResponse(json.dumps(output),
                        content_type='application/json')


def flatpages_link_list(request):
    """
    Returns a HttpResponse whose content is a Javascript file representing a
    list of links to flatpages.
    """
    from django.contrib.flatpages.models import FlatPage
    link_list = [(page.title, page.url) for page in FlatPage.objects.all()]
    return render_to_link_list(link_list)


def compressor(request):
    """
    Returns a GZip-compressed response.
    """
    return gzip_compressor(request)


def render_to_link_list(link_list):
    """
    Returns a HttpResponse whose content is a Javascript file representing a
    list of links suitable for use wit the TinyMCE external_link_list_url
    configuration option. The link_list parameter must be a list of 2-tuples.
    """
    return render_to_js_vardef('tinyMCELinkList', link_list)


def render_to_image_list(image_list):
    """
    Returns a HttpResponse whose content is a Javascript file representing a
    list of images suitable for use wit the TinyMCE external_image_list_url
    configuration option. The image_list parameter must be a list of 2-tuples.
    """
    return render_to_js_vardef('tinyMCEImageList', image_list)


def render_to_js_vardef(var_name, var_value):
    output = "var {!s} = {!s};".format(var_name, json.dumps(var_value))
    return HttpResponse(output, content_type='application/x-javascript')


def filebrowser(request):
    try:
        fb_url = request.build_absolute_uri(reverse('fb_browse'))
    except Exception:
        fb_url = request.build_absolute_uri(reverse('filebrowser:fb_browse'))

    return render(
        request,
        'tinymce/filebrowser.js',
        {'fb_url': fb_url},
        content_type='application/javascript'
    )

myapp/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render
from myapp.blog_page import getblog_bypage
from myapp.models import *



def New_article(request):
    article_list = Article.objects.all()
    page = getblog_bypage(request, article_list)
    return render(request,'index.html',locals())

def  category(request,cid):    #文章种类表选择
    article_list = Article.objects.filter(category_name_id=cid)    #根据models中Article的多对一关联关系，选择这个种类的所有文章
    page = getblog_bypage(request,article_list)
    return render(request,'index.html',locals())

def acticle_page(request):      #分页
    cid = request.GET.get("cid")
    if cid:
        article_list = Article.objects.filter(category_name_id=cid)
        page = getblog_bypage(request,article_list)
        return  render(request,'index.html',locals())
    else:
        article_list=Article.objects.all()
        page = getblog_bypage(request,article_list)
        return render(request,'index.html',locals())


def article(request):  #根据标题查看文章
    aid = request.GET.get('aid')
    article=Article.objects.get(id=aid)
    comment_list = article.comment_set.all()
    return render(request,'article.html',locals())

def reg(request):  #进入注册界面
    return render(request,'reg.html')


def reg1(request):  #注册用户信息
        regname = request.POST.get('regname')
        regeamil = request.POST.get('regemil')
        regphone = request.POST.get('regphone')
        regpwd = request.POST.get('regpwd')
        Myuser.objects.create_user(username=regname,email=regeamil,phone=regphone,password=regpwd)
        return HttpResponseRedirect('/myapp/login/')

def gologin(request):  #进入登录界面
    return render(request,'login.html')
def login1(request,aid): #登录
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(username=username,password=password)
    if user:
        login(request,user)
        return HttpResponseRedirect('/myapp/article/?aid/')
    else:
        return render(request,'login.html')

def log_out(request):   # 注销
    logout(request)
    return render (request,'index.html')

def cmt1(request,aid):  #根据标题查看文章进行评论
    content = request.POST.get('cmtname')
    name = request.POST.get('name')
    Comment.objects.create(username=name,content=content,article_comment_id=aid)
    return HttpResponseRedirect('/myapp/article/?aid='+aid)

myapp/templates/ad.html
{% load static %}
<div class="banner">
      <div id="slide-holder">
        <div id="slide-runner"> <a href="/" target="_blank"><img id="slide-img-1" src="{% static 'images/a1.jpg' %}"  alt="" /></a> <a href="/" target="_blank"><img id="slide-img-2" src="{% static 'images/a2.jpg' %}"  alt="" /></a> <a href="/" target="_blank"><img id="slide-img-3" src="{% static 'images/a3.jpg' %}"  alt="" /></a> <a href="/" target="_blank"><img id="slide-img-4" src="{% static 'images/a4.jpg' %}"  alt="" /></a>
          <div id="slide-controls">
            <p id="slide-client" class="text"><strong></strong><span></span></p>
            <p id="slide-desc" class="text"></p>
            <p id="slide-nav"></p>
          </div>
        </div>
      </div>
      <script>
    if(!window.slider) {
    var slider={};
  }

  slider.data= [
    {
        "id":"slide-img-1", // 与slide-runner中的img标签id对应
        "client":"标题1",
        "desc":"这里修改描述 这里修改描述 这里修改描述" //这里修改描述
    },
    {
        "id":"slide-img-2",
        "client":"标题2",
        "desc":"add your description here"
    },
    {
        "id":"slide-img-3",
        "client":"标题3",
        "desc":"add your description here"
    },
    {
        "id":"slide-img-4",
        "client":"标题4",
        "desc":"add your description here"
    }
  ];

    </script>
    </div>
    <!-- banner代码 结束 -->

myapp/templates/article.html
{% extends 'base.html' %}
{% load static %}
{% load comment %}
{#{% load myfilter %}#}
{% block left_content %}
    <div class="postdate">
      <div class="month">{{ article.date_publish }}</div>
      <div class="date">{{ article.date_publish | date:'d' }}</div>
    </div>
    <div class="title">
        <h2><a href="" rel="bookmark" title="{{ article.title }}">{{ article.title }}</a></h2>
        <div class="postmeta">
          <span class="postmeta_author">{{ article.user.username }}</span>
          <span class="postmeta_category"><a href="" rel="category">{{ article.category.name }}</a></span>
          <span class="postmeta_time">{{ article.date_publish | date:'Y-m-d' }}</span>
        </div>
    </div>
        <div class="entry">
          {{ article.content | safe }}
        </div>
        <span class="tags">
            {% for tag in article.tag.all %}
            <a href="?tag={{ tag.name }}" rel="tag">{{ tag.name }}</a>
            {% endfor %}

        </span>

        <div class="info">
        Address:  <a href="{{ SITE_URL }}article/?id={{ article.id }}" rel="bookmark" title="{{ article.title }}">{{ SITE_URL }}article/?id={{ article.id }}</a>
        </div>

{#      <div class="commentstitle"><h3 id="comments"><span class="commentsnumber">only 1 comment</span> untill now</h3></div>#}
        {% comment_tree comment_list   %}
{#      <ol class="commentlist">#}
{#          {% for comment in comment_list %}#}
{#          <li id="comment-59418">#}
{#                <div class="top"><a href='{{ comment.url }}' rel='external nofollow' class='url'>{{ comment.username }}</a><span class="time"> @ <a href="#comment-59418" title="">{{ comment.date_publish | date:'Y-m-d ' }}</a></span></div>#}
{#                <div><img alt='' src='{% static 'images/default.jpg' %}' class='avatar avatar-32 photo' height='32' width='32' /></div>#}
{##}
{#                <div class="body">#}
{#                                <p>{{ comment.content }}</p>#}
{#                </div>#}
{#          </li>#}
{##}
{#          {% endfor %}#}
{#      </ol>#}

    <div id="commentform">
    <h3 id="respond">Add your comment now</h3>
    {% if not request.user.is_authenticated %}
    <div class='login_info'>还没有登陆？可以登录后再评论哦。<b><a href="{% url 'myapp:login' %}">&raquo;去登录</a>&nbsp;<a href="{% url 'myapp:reg' %}">&raquo;去注册</a></b></div>
    {% else %}
    <div class='login_info'><b>{{ request.user.username }}</b>,快来写点评论吧!&nbsp;<a href="{% url 'myapp:logout' %}">注销</a></div>
    {% endif %}
    <form action="{% url 'myapp:cmt1' article.id %}" method="post" >
        {% csrf_token %}
    <div>
      用户<input type="text" name="name" >
    </div>
    <div>
     <textarea name="cmtname" ></textarea>
     <input type="submit" value="评论" >

    </div>


{#    {% csrf_token %}#}
{#    <p>{{ comment_form.author }}#}
{#    <label for="author">Name (required)</label></p>#}
{##}
{#    <p>{{ comment_form.email }}#}
{#    <label for="email">Email (Will NOT be published) (required)</label></p>#}
{##}
{#    <p>{{ comment_form.phone }}#}
{#    <label for="phone">URL</label></p>#}
{##}
{#    <!--<p><small><strong>XHTML:</strong> You can use these tags: &lt;a href=&quot;&quot; title=&quot;&quot;&gt; &lt;abbr title=&quot;&quot;&gt; &lt;acronym title=&quot;&quot;&gt; &lt;b&gt; &lt;blockquote cite=&quot;&quot;&gt; &lt;cite&gt; &lt;code class=&quot;&quot; title=&quot;&quot; data-url=&quot;&quot;&gt; &lt;del datetime=&quot;&quot;&gt; &lt;em&gt; &lt;i&gt; &lt;q cite=&quot;&quot;&gt; &lt;strike&gt; &lt;strong&gt; &lt;pre class=&quot;&quot; title=&quot;&quot; data-url=&quot;&quot;&gt; &lt;span class=&quot;&quot; title=&quot;&quot; data-url=&quot;&quot;&gt; </small></p>-->#}
{##}
{#    <p>{{ comment_form.comment }}</p>#}
{##}
{#    <p>#}
{#        {{ comment_form.article }}#}
{#        <input name="submit" type="submit" id="submit" tabindex="5" value="提交   " class="button" />#}
{#    </p>#}
{#    </form>#}
    </div>
{% endblock %}

myapp/templates/base.html
{% load static %}
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>  </title>
<meta name="keywords" content=" " />
<meta name="description" content=" " />
<link href="{% static 'css/base.css' %}" rel="stylesheet">
<link href="{% static 'css/index.css' %}" rel="stylesheet">
{% block custom_css %}{% endblock %}
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/sliders.js' %}"></script>
<!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
{% block custom_js %}{% endblock %}
</head>
<body>
<header>
  <div class="logo">
      <h1>{{ Blog_name }} </h1>
      <p>{{ Blog_desc }} </p>
  </div>
  <nav id="topnav" class="f_r">
    <ul>
      <a href="{% url 'myapp:first' %}">首页</a>
      {% for category in category_list %}
      <a href="{% url 'myapp:category' category.id %}">{{ category.name }}</a>
      {% endfor %}
    </ul>
    <script src="{% static 'js/nav.js' %}"></script>
  </nav>
</header>
<article>
  <div class="l_box f_l">
      {% block left_content %}{% endblock %}
  </div>
  <div class="r_box f_r">
    <div class="tit01">
      <h3>关注我</h3>
      <div class="gzwm">
        <ul>
          <li><a class="xlwb" href="#" target="_blank">新浪微博</a></li>
          <li><a class="txwb" href="#" target="_blank">腾讯微博</a></li>
          <li><a class="rss" href="" target="_blank">RSS</a></li>
          <li><a class="wx" href="mailto:admin@admin.com">邮箱</a></li>
        </ul>
      </div>
    </div>
    <!--tit01 end-->
    <div class="moreSelect" id="lp_right_select">
      <script>
window.onload = function ()
{
  var oLi = document.getElementById("tab").getElementsByTagName("li");
  var oUl = document.getElementById("ms-main").getElementsByTagName("div");

  for(var i = 0; i < oLi.length; i++)
  {
    oLi[i].index = i;
    oLi[i].onmouseover = function ()
    {
      for(var n = 0; n < oLi.length; n++) oLi[n].className="";
      this.className = "cur";
      for(var n = 0; n < oUl.length; n++) oUl[n].style.display = "none";
      oUl[this.index].style.display = "block"
    }
  }
}
</script>
      <div class="ms-top">
        <ul class="hd" id="tab">
          <li class="cur"><a href="/">浏览排行</a></li>
          <li><a href="/">评论排行</a></li>
          <li><a href="/">站长推荐</a></li>
        </ul>
      </div>
      <div class="ms-main" id="ms-main">
        <div style="display: block;" class="bd bd-news" >
          <ul>
            <li><a href="/" target="_blank">住在手机里的朋友</a></li>
            <li><a href="/" target="_blank">教你怎样用欠费手机拨打电话</a></li>
            <li><a href="/" target="_blank">原来以为，一个人的勇敢是，删掉他的手机号码...</a></li>
            <li><a href="/" target="_blank">手机的16个惊人小秘密，据说99.999%的人都不知</a></li>
            <li><a href="/" target="_blank">你面对的是生活而不是手机</a></li>
            <li><a href="/" target="_blank">豪雅手机正式发布! 在法国全手工打造的奢侈品</a></li>
          </ul>
        </div>
        <div  class="bd bd-news">
          <ul>
            {% for article in article_comment_list %}
            <li><a href="/" target="_blank"> </a></li>
            {% endfor %}
          </ul>
        </div>
        <div class="bd bd-news">
          <ul>
            <li><a href="/" target="_blank">手机的16个惊人小秘密，据说99.999%的人都不知</a></li>
            <li><a href="/" target="_blank">你面对的是生活而不是手机</a></li>
            <li><a href="/" target="_blank">住在手机里的朋友</a></li>
            <li><a href="/" target="_blank">豪雅手机正式发布! 在法国全手工打造的奢侈品</a></li>
            <li><a href="/" target="_blank">教你怎样用欠费手机拨打电话</a></li>
            <li><a href="/" target="_blank">原来以为，一个人的勇敢是，删掉他的手机号码...</a></li>
          </ul>
        </div>
      </div>
      <!--ms-main end -->
    </div>
    <!--切换卡 moreSelect end -->

    <div class="cloud">
      <h3>标签云</h3>
      <ul>
        <li><a href="/">个人博客</a></li>
        <li><a href="/">web开发</a></li>
        <li><a href="/">前端设计</a></li>
        <li><a href="/">Html</a></li>
        <li><a href="/">CSS3</a></li>
        <li><a href="/">Html5+css3</a></li>
        <li><a href="/">百度</a></li>
        <li><a href="/">Javasript</a></li>
        <li><a href="/">web开发</a></li>
        <li><a href="/">前端设计</a></li>
        <li><a href="/">Html</a></li>
        <li><a href="/">CSS3</a></li>
        <li><a href="/">Html5+css3</a></li>
        <li><a href="/">百度</a></li>
      </ul>
    </div>
    <div class="tuwen">
      <h3>文章归档</h3>
      <ul>
        {% for archive in archive_list %}
        <li>
          <p><span class="tutime font-size-18"><a href='{% url 'archive' %}?year={{ archive | slice:":4" }}&month={{ archive | slice:"5:7" }}'>{{ archive }}</a></span></p>
        </li>
        {% endfor %}
      </ul>
    </div>
    <div class="links">
      <h3>友情链接</h3>
      <ul>
        <li><a href="/">web开发</a></li>
        <li><a href="/">前端设计</a></li>
        <li><a href="/">Html</a></li>
        <li><a href="/">CSS3</a></li>
        <li><a href="/">Html5+css3</a></li>
        <li><a href="/">百度</a></li>
      </ul>
    </div>
  </div>
  <!--r_box end -->
</article>
<footer>
  <p class="ft-copyright">某人的个人博客</p>
  <div id="tbox"> <a id="togbook" href="/"></a> <a id="gotop" href="javascript:void(0)"></a> </div>
</footer>
</body>
</html>

myapp/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block left_content %}
    {% include 'ad.html' %}
    <div class="topnews">
      <h2>最新文章</h2>
      {% for article in page %}
      <div class="blogs">
        <ul>
          <h3><a href="{% url 'myapp:article' %}?aid={{ article.id }}">{{ article.title }} </a></h3>
          <p> {{ article.desc }} </p>
          <p class="autor"><span class="lm f_l">{% for tag in article.tag.all %}<a href="/">{{ tag.name }}</a>&nbsp;</span>{% endfor %}<span class="dtime f_l">{{ article.date_publish | date:'Y-m-d' }}</span><span class="viewnum f_r">浏览（<a href="/">{{ article.click_count }}</a>）</span><span class="pingl f_r">评论（<a href="/">{{ article.comment_set.all.count }}</a>）</span></p>
        </ul>
      </div>
      {% endfor %}
    </div>
    {% include 'pagination.html' %}
{% endblock %}

myapp/templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
		<meta charset="utf-8">
		<link href="{% static 'css/reglogin.css' %}" rel='stylesheet' type='text/css' />
		<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<div class="main">
		<div class="header" >
			<h1>Login!</h1>
		</div>
		<p></p>
			<form action="{% url 'myapp:login1' %}" method="post">
                {% csrf_token %}
				<ul class="right-form">
					<h2>Login:</h2>
					<li><input type="text" name="username" placeholder="Username" required/></li>
					<li><input type="password" name="password" placeholder="Password" required/></li>
                    <input type="submit" value="Login" >
					<div class="clear"> </div>
				</ul>
				<div class="clear"> </div>

			</form>
	</div>
</body>
</html>

myapp/templates/pagination.html
<div id="pagination">
    <ul id="pagination-flickr">
    {% if page.has_previous %}
    <li class="previous"><a href="{% url 'myapp:acticle_page' %}?cid={{ cid }}&page={{ page.previous_page_number }}">&laquo;上一页</a></li>
    {% else %}
    <li class="previous-off">&laquo;上一页</li>
    {% endif %}
     <li class="active">/</li>
    {% if page.has_next %}
      <li class="next"><a href="{% url 'myapp:acticle_page' %}?cid={{ cid }}&page={{ page.next_page_number }}">下一页 &raquo;</a></li>
    {% else %}
      <li class="next-off">下一页 &raquo;</li>
    {% endif %}
   </ul>
</div>

myapp/templates/reg.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
		<meta charset="utf-8">
		<link href="{% static 'css/reglogin.css' %}" rel='stylesheet' type='text/css' />
		<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

	<div class="main">
		<div class="header" >
			<h1>Create a Free Account!</h1>
		</div>
		<p></p>
			<form action="{% url 'myapp:reg1' %}" method="post">
                {% csrf_token %}
				<ul class="left-form">
					<h2>New Account:</h2>
					<li>
						注册名:<input type="text" name="regname"/>
						<div class="clear"> </div>
					</li> 
					<li>
						注册邮箱:<input type="email" name="regemail"/>
						<div class="clear"> </div>
					</li> 
					<li>
						注册微信:<input type="text" name="regphone"/>
						<div class="clear"> </div>
					</li> 
					<li>
						注册密码:<input type="password" name="regpwd"/>
						<div class="clear"> </div>
					</li>
                    <input type="hidden" name="source_url" value="{{ request.META.HTTP_REFERER }}">
					<input type="submit" value="Create And Login">
					<div class="clear"> </div>
				</ul>
				<div class="clear"> </div>
			</form>
	</div>
</body>
</html>